[tool.poetry]
name = "agentic-research-workflow"
version = "0.1.0"
authors = ["Shoaib"]

[tool.poetry.dependencies]
python = "^3.11"
langgraph = "^0.6.7"
pydantic = "^2.11.7"
langchain = "^0.3.27"
langchain-ollama = "^0.3.7"
fastapi = "^0.116.1"
uvicorn = "^0.35.0"
